channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =1.4.1
  - pyyaml =6.0
  - jinja2 =3.1.1
  - paramiko =2.10.3
  - tqdm =4.64.0
  - openssl <2
