channels:
  - conda-forge
dependencies:
  - defusedxml >=0.6.0
  - coveralls
  - coverage
  - codacy-coverage
  - pandas >=1.2.1
  - pyyaml >=5.4.1
  - jinja2 >=2.11.2
  - paramiko >=2.4.2
  - tqdm >=4.56.0
