channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =1.4.1
  - pyyaml =6.0
  - jinja2 =3.0.3
  - paramiko =2.9.2
  - tqdm =4.63.0
  - openssl <2
