channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =1.3.2
  - pyyaml =5.4.1
  - jinja2 =3.0.1
  - paramiko =2.7.2
  - tqdm =4.62.0
