channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.1
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =1.3.5
  - pyyaml =6.0
  - jinja2 =3.0.3
  - paramiko =2.8.1
  - tqdm =4.62.3
  - openssl =3.0.0
