channels:
  - conda-forge
dependencies:
  - defusedxml =0.7.0
  - coveralls
  - coverage
  - codacy-coverage
  - pandas =1.2.3
  - pyyaml =5.4.1
  - jinja2 =2.11.3
  - paramiko =2.7.2
  - tqdm =4.58.0
